<?php
/**
 * Created by PhpStorm.
 * User: zorochen
 * Date: 2016/11/23
 * Time: 上午1:06
 */

namespace app\controllers;


use app\base\BaseController;
use filsh\yii2\oauth2server\controllers\DefaultController;

class AuthController extends BaseController
{
    public  $modelClass='';
    public function actions()
    {
        $act = parent::actions();
        $act['index'] = $this->aIndex();
        return $act; // TODO: Change the autogenerated stub
    }


    private function aIndex(){

        $module = \Yii::$app->getModule('oauth2');
        $server = $module->getServer();
        $request = $module->getRequest();
        $response = $server->handleTokenRequest($request);

        return $response->getParameters();
    }
}