<?php
/**
 * Created by PhpStorm.
 * User: zorochen
 * Date: 2016/11/20
 * Time: 上午12:21
 */

namespace app\controllers;


use app\base\BaseController;

class BookingController extends BaseController
{
    public $modelClass = "app\dao\UserInfo";


    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }
}