<?php
/**
 * Created by PhpStorm.
 * User: zorochen
 * Date: 2016/11/20
 * Time: 上午1:30
 */

namespace app\base;


use yii\filters\AccessControl;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\ContentNegotiator;
use yii\filters\RateLimiter;
use yii\filters\VerbFilter;
use yii\rest\ActiveController;
use yii\web\Response;

class BaseController extends ActiveController
{

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::className(),
            'authMethods' => [
                ['class' => HttpBearerAuth::className()],
                ['class' => QueryParamAuth::className(), 'tokenParam' => 'access_token'],
            ]
        ];
        $behaviors['contentNegotiator'] = [
            'class' => ContentNegotiator::className(),
            'except' => [],
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ],
        ];
        $behaviors['verbFilter']  = [
            'class' => VerbFilter::className (),
            'actions' => $this->verbs ()
        ];
        $behaviors['rateLimiter'] = [
            'class' => RateLimiter::className ()
        ];

        return $behaviors;
    }

    public function checkAccess($action, $model = null, $params = [])
    {
        var_dump("hello");die();
        parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result) {

        $result = [
            'code' 		=> 0,
            'message' 	=> 'success',
            'data' 		=> $result,
        ];

        return $result;
    }
}